### ISSUE TITLE
dApp connector

### ISSUE THREAD

**Issue by Lartyste** [ThierryM1212/SAFEW#12]
Hi i have issue with dApp connector of SAFEW(chrome extension):

The extension doesnt test if ergo_request_read_access() already exist before to replace its code, same for ergoConnector.nautilus.connect(). It's in inject.js or something like that..

Its a problem if i have Yoroi and Nautilus on my browser. I tried with ergoAuctionHouse and Safew is launched instead of Yoroi. Dont have this problem with Nautilus. Maybe its a deliberate choice of your dev...i dont know, but i prefer to tell you.

Hope this can help you to improve SAFEW^^

Bye

**Comment by ThierryM1212** [comment]
Hi,
Thanks for reporting the issue.
This should be improved soon with official support of SAFEW in the Ergodex, currently it "needs" to declare ergoConnector.nautilus.connect() because the ergoConnector.safew.connect() is not called by Ergodex.

On ergoAuctionHouse, the connection is done with "ergo_request_read_access()" which needs to be declared by all wallets following EIP-12 standard. I'm not sure how the concurrency on this method needs to be handled, it is now deprecated for the new ergoConnector.

I would recommend to avoid to have 2 ergo wallets with a dApp connector enabled in the same browser.

I would expect in the future dApps that the list of the available wallet to connect could be built by listing the ergoConnector attributes.

Regards

**Comment by Mercellino** [comment]
> Hi i have issue with dApp connector of SAFEW(chrome extension):
> 
> The extension doesnt test if ergo_request_read_access() already exist before to replace its code, same for ergoConnector.nautilus.connect(). It's in inject.js or something like that..
> 
> Its a problem if i have Yoroi and Nautilus on my browser. I tried with ergoAuctionHouse and Safew is launched instead of Yoroi. Dont have this problem with Nautilus. Maybe its a deliberate choice of your dev...i dont know, but i prefer to tell you.
> 
> Hope this can help you to improve SAFEW^^
> 
> Bye

**Comment by ThierryM1212** [comment]
This overridde allows to use SAFEW even if only Nautilus or Yoroi support is implemented by the dApp.
SAFEW extension needs to be disabled, to uses the other Ergo wallet implementing the dApp connector.
