### ISSUE TITLE
QR code won't show with ErgoPay

### ISSUE THREAD

**Issue by varmsaus** [ThierryM1212/SAFEW#13]
More often than not, the QR code will not show up with ErgoPay. I'm using a cold android wallet to sign transactions. I can't swap on ErgoDEX or list/buy NFTs on SkyHarbor etc. edit: I'm using Brave browser for windows.

![image](https://user-images.githubusercontent.com/47339265/166646306-f31e483b-3369-42c6-b90f-367313a5663b.png)

**Comment by varmsaus** [comment]
Nothing happens when I click "Open wallet app"

**Comment by ThierryM1212** [comment]
Thanks for reporting the issue.

This occurs for me when the transaction is "too big", and the QR code fails to be generated.
This is a limitation for transaction signed through QR code, around 4000 characters in the json of the transaction.
I will try to add a proper error message.

This may occurs because your wallet includes many unspent boxes.
As a workaround, you could try to consolidate your wallet before the transaction, by issuing a transaction to yourself, with all the wallet content. This should reduce the size of the ergodex transaction enough so it can be encoded in the QR code.

"Open wallet app": It works only to my knowledge on Android using SAFEW in Kiwi browser. It will open the Android Wallet to propose to sign the transaction. It could be used on Windows probably if a native wallet implement the feature.
This could also workaround your transaction size issue as the transaction will be sent to Android Wallet without QR code.

A future solution, will be the implementation of the second part of the Ergopay standard, with the "Ergopay payment request"...

**Comment by ThierryM1212** [comment]
The issue is now resolved on desktop using the Mosaic desktop wallet and applying the .reg file to link the wallet to Ergopay requests at OS level.
SAFEW can now delegate the transaction signing to Mosaic on desktop, Terminus wallet on iOS and ERgo wallet on Android.
