### ISSUE TITLE
does not install on "Decentr" browser

### ISSUE THREAD

**Issue by Pimsta** [ThierryM1212/SAFEW#21]
"Invalid manifest" error. Tried installing through extension chrome extension store and load unpacking manually.
chrome based browser, crypto focused like brave

**Comment by ThierryM1212** [comment]
Thanks, but I rather think the support of manifest v3 extension will/should be added to Decentr.

SAFEW has migrated to manifest v3 because the Chrome web store does not allow anymore new manifest v2 extensions.
In June 2023, it is planed that manifest v2 extensions won't run anymore in Chrome.

https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/
